"""
Ablation study over the divergence-oracle portfolio (100_STEPS step 53).

An ablation justifies each component: if removing a single divergence-class
oracle leaves some genuinely-divergent units undetected, that oracle earns its
place. This module turns that argument into measured numbers over the *same*
labelled benchmark used for precision/recall (:mod:`metrics`), so the claim is
reproducible rather than rhetorical.

For each registered class ``K`` we recompute the portfolio's symbolic recall with
``K``'s oracle disabled and report:

* ``newly_missed`` — the positive units that the full portfolio detects but the
  ablated portfolio does not. These are exactly the divergences *uniquely* owed
  to ``K``; their existence is the justification for keeping ``K``.
* ``recall_full`` vs ``recall_ablated`` — the portfolio-level recall drop.
* ``cross_class_leak`` — positives of a *different* class that flip to missed
  when ``K`` is removed. A correctly-scoped oracle causes **zero** leak; a
  non-zero value would expose an oracle that was secretly covering for another.

Everything here is deterministic and toolchain-free (pure symbolic decisions),
so it can be regenerated byte-identically.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Set

from .metrics import POSITIVE_CASES, LabeledCase
from .plugin import REGISTRY, OracleVerdict


def _detected_by(case: LabeledCase, disabled: Set[str]) -> bool:
    """Whether *any* enabled oracle symbolically flags ``case`` as divergent."""
    for key, oracle in REGISTRY.items():
        if key in disabled:
            continue
        if not oracle.applies_to(case.unit):
            continue
        if oracle.find_divergence(case.unit).verdict is OracleVerdict.DIVERGENT:
            return True
    return False


def _recall(positives: List[LabeledCase], disabled: Set[str]) -> float:
    if not positives:
        return 1.0
    hit = sum(1 for c in positives if _detected_by(c, disabled))
    return hit / len(positives)


@dataclass
class AblationRow:
    divergence_class: str
    recall_full: float
    recall_ablated: float
    newly_missed: List[str] = field(default_factory=list)
    cross_class_leak: List[str] = field(default_factory=list)

    @property
    def recall_drop(self) -> float:
        return self.recall_full - self.recall_ablated

    def as_dict(self) -> Dict:
        return {
            "divergence_class": self.divergence_class,
            "recall_full": self.recall_full,
            "recall_ablated": self.recall_ablated,
            "recall_drop": self.recall_drop,
            "newly_missed": sorted(self.newly_missed),
            "cross_class_leak": sorted(self.cross_class_leak),
        }


def ablate_each_class(positives: List[LabeledCase] = None) -> Dict:
    """Disable each oracle in turn and measure what its absence misses.

    Returns a deterministic, JSON-serialisable report (keys sorted).
    """
    positives = positives if positives is not None else POSITIVE_CASES
    recall_full = _recall(positives, set())
    # which positives the full portfolio detects (baseline truth of detectability)
    detected_full = {c.name for c in positives if _detected_by(c, set())}

    rows: List[AblationRow] = []
    for key in sorted(REGISTRY):
        disabled = {key}
        detected_ablated = {c.name for c in positives if _detected_by(c, disabled)}
        newly = detected_full - detected_ablated
        # a leak is a newly-missed positive whose true class is NOT `key`.
        truth_of = {c.name: c.truth_class for c in positives}
        leak = [n for n in newly if truth_of.get(n) != key]
        rows.append(AblationRow(
            divergence_class=key,
            recall_full=recall_full,
            recall_ablated=_recall(positives, disabled),
            newly_missed=list(newly),
            cross_class_leak=leak,
        ))

    return {
        "recall_full": recall_full,
        "num_positives": len(positives),
        "per_class": {r.divergence_class: r.as_dict() for r in rows},
        "note": (
            "newly_missed lists positives detected by the full portfolio but not "
            "after disabling this class; cross_class_leak should be empty for a "
            "correctly-scoped oracle (each oracle covers only its own class)."
        ),
    }
