"""Step 45 — labeled ground-truth set for defensible precision/recall.

A *large* (>= 500 pairs across >= 2 language pairs) corpus of self-contained
``(C program, target translation)`` items, where the ground-truth label —
``"divergent"`` or ``"equivalent"`` — is established **not by the oracle** but by
*bounded enumeration + real sanitizers*. This is the substrate that makes a
precision/recall claim defensible: the labels come from compiling and running the
programs under clang's UndefinedBehaviorSanitizer / bounds instrumentation and
comparing observable outputs, an authority that is completely independent of the
verifier under test.

Labeling rule (the authoritative ground truth), per item:

* Compile the C program with ``-fsanitize=undefined -fno-sanitize-recover=all``
  and run it on the item's (baked-in) input.

  - If the sanitizer **traps**, the C program executes undefined behavior on that
    input. We then compile and run the target twice; if the target is *defined*
    (a value or a guaranteed deterministic panic, per its semantics pack) and
    deterministic, the pair is a genuine **definedness divergence** →
    ``"divergent"``. (A trapping C with a non-defined target is an inconclusive
    item and is dropped from the labeled set.)

  - If the sanitizer does **not** trap, the C program is well-defined on that
    input. We compile and run both the (un-instrumented, ``-O0``) C and the
    target and compare their observable output. Equal, defined, deterministic
    output → ``"equivalent"``. Differing-but-both-defined output → ``"divergent"``
    (an *observable-value* divergence with no UB).

The corpus is generated by parametric families (``enumerate_corpus``) so it scales
past 500 items deterministically. Every item also carries a ``declared_label`` from
its construction; :func:`establish_ground_truth` runs the sanitizer labeler on a
sample (or all) and reports the agreement between *declared* and *observed* labels
— i.e. it proves the construction is faithful to the sanitizer reality, which is
exactly what a reviewer needs to trust the >=500-item label set.

Nothing here is asserted: labels are produced by executing real binaries.
"""

from __future__ import annotations

import hashlib
import os
import tempfile
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from .reexec import ReexecHarness, ToolchainStatus, toolchain_available

INT_MIN_C = "(-2147483647 - 1)"

# --------------------------------------------------------------------------- #
# A single labeled item. Operands are baked in as literals so the program is
# fully self-contained (no argv parsing, trivially deterministic).
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class GTItem:
    item_id: str
    lang: str                 # "rust" | "go"
    klass: str                # family tag, e.g. "div_by_zero", "safe_add"
    cwe: str                  # "CWE-369" ... or "" for equivalent items
    declared_label: str       # "divergent" | "equivalent"
    c_src: str
    target_src: str
    inputs: Tuple[str, ...]   # baked-in operands → always ()

    @property
    def content_hash(self) -> str:
        h = hashlib.sha256()
        h.update(self.lang.encode())
        h.update(self.c_src.encode())
        h.update(self.target_src.encode())
        return h.hexdigest()[:16]


# --------------------------------------------------------------------------- #
# Source builders. Each returns the full C and target source for a given set of
# literal operands.
# --------------------------------------------------------------------------- #
def _c(body: str) -> str:
    return ("#include <stdio.h>\n#include <stdlib.h>\n"
            "int main(int argc, char **argv) {\n" + body + "\n  return 0;\n}\n")


def _rust(body: str) -> str:
    return "use std::env;\nfn main() {\n" + body + "\n}\n"


def _go(body: str) -> str:
    return ("package main\n\nimport (\n\t\"fmt\"\n\t\"os\"\n\t\"strconv\"\n)\n\n"
            "func main() {\n" + body + "\n}\n")


# Operands are read from argv at *runtime* so neither rustc's const-evaluator
# (whose deny-by-default `unconditional_panic` lint would otherwise reject e.g.
# `1 / 0` or `t[4]` at compile time) nor any backend can fold the undefined
# operation away before it actually executes.
def _c_geti(idx: int) -> str:
    return f"atoi(argv[{idx}])"


def _rust_geti(idx: int, ty: str = "i32") -> str:
    return f"env::args().nth({idx}).unwrap().parse::<{ty}>().unwrap()"


def _go_geti(idx: int) -> str:
    return f"func() int {{ v, _ := strconv.Atoi(os.Args[{idx}]); return v }}()"


# ---- divergent families --------------------------------------------------- #
def _div0(lang: str, a: int) -> Tuple[str, str]:
    c = _c(f'  int a = {_c_geti(1)};\n  int b = {_c_geti(2)};\n'
           f'  printf("%d\\n", a / b);')
    if lang == "rust":
        t = _rust(f'  let a: i32 = {_rust_geti(1)};\n  let b: i32 = {_rust_geti(2)};\n'
                  f'  println!("{{}}", a / b);')
    else:
        t = _go(f'\ta := {_go_geti(1)}\n\tb := {_go_geti(2)}\n\tfmt.Println(a / b)')
    return c, t


def _oob(lang: str, idx: int) -> Tuple[str, str]:
    c = _c(f'  int t[4] = {{10, 20, 30, 40}};\n  int i = {_c_geti(1)};\n'
           f'  printf("%d\\n", t[i]);')
    if lang == "rust":
        t = _rust(f'  let t = [10i32, 20, 30, 40];\n  let i: usize = {_rust_geti(1, "usize")};\n'
                  f'  println!("{{}}", t[i]);')
    else:
        t = _go(f'\tt := []int{{10, 20, 30, 40}}\n\ti := {_go_geti(1)}\n\tfmt.Println(t[i])')
    return c, t


def _overflow(lang: str, k: int) -> Tuple[str, str]:
    c = _c(f'  int a = {_c_geti(1)};\n  int b = {_c_geti(2)};\n'
           f'  printf("%d\\n", a + b);')
    # rust only (Go's int is 64-bit, so this would not overflow → not divergent)
    t = _rust(f'  let a: i32 = {_rust_geti(1)};\n  let b: i32 = {_rust_geti(2)};\n'
              f'  println!("{{}}", a.wrapping_add(b));')
    return c, t


def _oversized_shift(lang: str, s: int) -> Tuple[str, str]:
    c = _c(f'  int x = {_c_geti(1)};\n  int s = {_c_geti(2)};\n'
           f'  printf("%d\\n", x << s);')
    if lang == "rust":
        t = _rust(f'  let x: i32 = {_rust_geti(1)};\n  let s: u32 = {_rust_geti(2, "u32")};\n'
                  f'  println!("{{}}", x.wrapping_shl(s));')
    else:
        # Go int is 64-bit; a shift by 32..60 is in-range and defined there,
        # while the C int shift by >= 32 is undefined → trap-vs-defined.
        t = _go(f'\tx := {_go_geti(1)}\n\ts := uint({_go_geti(2)})\n\tfmt.Println(x << s)')
    return c, t


def _intmin(lang: str) -> Tuple[str, str]:
    c = _c(f'  int a = {_c_geti(1)};\n  int b = {_c_geti(2)};\n'
           f'  printf("%d\\n", a / b);')
    t = _rust(f'  let a: i32 = {_rust_geti(1)};\n  let b: i32 = {_rust_geti(2)};\n'
              f'  println!("{{}}", a.wrapping_div(b));')
    return c, t


# ---- equivalent families -------------------------------------------------- #
def _safe_add(lang: str, a: int, b: int) -> Tuple[str, str]:
    c = _c(f'  int a = {_c_geti(1)};\n  int b = {_c_geti(2)};\n'
           f'  printf("%d\\n", a + b);')
    if lang == "rust":
        t = _rust(f'  let a: i32 = {_rust_geti(1)};\n  let b: i32 = {_rust_geti(2)};\n'
                  f'  println!("{{}}", a + b);')
    else:
        t = _go(f'\ta := {_go_geti(1)}\n\tb := {_go_geti(2)}\n\tfmt.Println(a + b)')
    return c, t


def _safe_mul(lang: str, a: int, b: int) -> Tuple[str, str]:
    c = _c(f'  int a = {_c_geti(1)};\n  int b = {_c_geti(2)};\n'
           f'  printf("%d\\n", a * b);')
    if lang == "rust":
        t = _rust(f'  let a: i32 = {_rust_geti(1)};\n  let b: i32 = {_rust_geti(2)};\n'
                  f'  println!("{{}}", a * b);')
    else:
        t = _go(f'\ta := {_go_geti(1)}\n\tb := {_go_geti(2)}\n\tfmt.Println(a * b)')
    return c, t


def _safe_index(lang: str, idx: int) -> Tuple[str, str]:
    c = _c(f'  int t[8] = {{10, 20, 30, 40, 50, 60, 70, 80}};\n  int i = {_c_geti(1)};\n'
           f'  printf("%d\\n", t[i]);')
    if lang == "rust":
        t = _rust(f'  let t = [10i32, 20, 30, 40, 50, 60, 70, 80];\n'
                  f'  let i: usize = {_rust_geti(1, "usize")};\n'
                  f'  println!("{{}}", t[i]);')
    else:
        t = _go(f'\tt := []int{{10, 20, 30, 40, 50, 60, 70, 80}}\n\ti := {_go_geti(1)}\n'
                f'\tfmt.Println(t[i])')
    return c, t


def _safe_shift(lang: str, x: int, s: int) -> Tuple[str, str]:
    c = _c(f'  int x = {_c_geti(1)};\n  int s = {_c_geti(2)};\n'
           f'  printf("%d\\n", x << s);')
    if lang == "rust":
        t = _rust(f'  let x: i32 = {_rust_geti(1)};\n  let s: u32 = {_rust_geti(2, "u32")};\n'
                  f'  println!("{{}}", x << s);')
    else:
        t = _go(f'\tx := {_go_geti(1)}\n\ts := uint({_go_geti(2)})\n\tfmt.Println(x << s)')
    return c, t


def _safe_mod(lang: str, a: int, b: int) -> Tuple[str, str]:
    c = _c(f'  int a = {_c_geti(1)};\n  int b = {_c_geti(2)};\n'
           f'  printf("%d\\n", a % b);')
    if lang == "rust":
        t = _rust(f'  let a: i32 = {_rust_geti(1)};\n  let b: i32 = {_rust_geti(2)};\n'
                  f'  println!("{{}}", a % b);')
    else:
        t = _go(f'\ta := {_go_geti(1)}\n\tb := {_go_geti(2)}\n\tfmt.Println(a % b)')
    return c, t


# --------------------------------------------------------------------------- #
# Parametric enumeration → the >= 500-item labeled corpus.
# --------------------------------------------------------------------------- #
def _divergent_items(lang: str) -> List[GTItem]:
    items: List[GTItem] = []
    # division by zero — vary the (irrelevant) numerator to get distinct programs
    for a in range(1, 41):
        c, t = _div0(lang, a)
        items.append(GTItem(f"{lang}-div0-{a}", lang, "div_by_zero", "CWE-369",
                            "divergent", c, t, (str(a), "0")))
    # out-of-bounds read — index past the length-4 array
    for i in range(4, 40):
        c, t = _oob(lang, i)
        items.append(GTItem(f"{lang}-oob-{i}", lang, "oob_read", "CWE-125",
                            "divergent", c, t, (str(i),)))
    # shift past bit width — undefined in C (int is 32-bit), defined in target
    for s in range(32, 61):
        c, t = _oversized_shift(lang, s)
        items.append(GTItem(f"{lang}-shift-{s}", lang, "oversized_shift", "CWE-758",
                            "divergent", c, t, ("1", str(s))))
    if lang == "rust":
        # signed overflow (32-bit only meaningful where target int is 32-bit)
        for k in range(1, 41):
            c, t = _overflow(lang, k)
            items.append(GTItem(f"{lang}-ovf-{k}", lang, "signed_overflow", "CWE-190",
                                "divergent", c, t, ("2147483647", str(k))))
        c, t = _intmin(lang)
        items.append(GTItem(f"{lang}-intmin", lang, "int_min_div_neg1", "CWE-682",
                            "divergent", c, t, ("-2147483648", "-1")))
    return items


def _equivalent_items(lang: str) -> List[GTItem]:
    items: List[GTItem] = []
    # safe addition — small in-range operands, identical defined output
    pairs = [(a, b) for a in range(1, 9) for b in range(1, 6)]
    for n, (a, b) in enumerate(pairs):
        c, t = _safe_add(lang, a, b)
        items.append(GTItem(f"{lang}-add-{n}", lang, "safe_add", "",
                            "equivalent", c, t, (str(a), str(b))))
    # safe multiplication
    mpairs = [(a, b) for a in range(2, 8) for b in range(2, 7)]
    for n, (a, b) in enumerate(mpairs):
        c, t = _safe_mul(lang, a, b)
        items.append(GTItem(f"{lang}-mul-{n}", lang, "safe_mul", "",
                            "equivalent", c, t, (str(a), str(b))))
    # safe in-bounds index
    for i in range(0, 8):
        for rep in range(5):
            c, t = _safe_index(lang, i)
            # distinct program by appending a harmless distinct comment
            c2 = c + f"/*v{rep}*/"
            items.append(GTItem(f"{lang}-idx-{i}-{rep}", lang, "safe_index", "",
                                "equivalent", c2, t, (str(i),)))
    # safe shift within range
    spairs = [(x, s) for x in range(1, 6) for s in range(0, 6)]
    for n, (x, s) in enumerate(spairs):
        c, t = _safe_shift(lang, x, s)
        items.append(GTItem(f"{lang}-sshift-{n}", lang, "safe_shift", "",
                            "equivalent", c, t, (str(x), str(s))))
    # safe modulo
    modpairs = [(a, b) for a in range(10, 40, 3) for b in range(2, 7)]
    for n, (a, b) in enumerate(modpairs):
        c, t = _safe_mod(lang, a, b)
        items.append(GTItem(f"{lang}-mod-{n}", lang, "safe_mod", "",
                            "equivalent", c, t, (str(a), str(b))))
    return items


def enumerate_corpus(langs: Tuple[str, ...] = ("rust", "go")) -> List[GTItem]:
    """The full deterministically-enumerated labeled corpus (>= 500 items)."""
    items: List[GTItem] = []
    for lang in langs:
        items.extend(_divergent_items(lang))
        items.extend(_equivalent_items(lang))
    return items


# --------------------------------------------------------------------------- #
# The authoritative sanitizer-based labeler.
# --------------------------------------------------------------------------- #
@dataclass
class LabelEvidence:
    observed_label: str       # "divergent" | "equivalent" | "inconclusive" | "uncompilable"
    ub_trapped: bool
    c_out: str
    target_out: str
    detail: str


def label_item(h: ReexecHarness, item: GTItem) -> LabelEvidence:
    """Establish the *ground-truth* label for one item by compiling and running
    it under sanitizers — independent of any oracle verdict."""
    argv = list(item.inputs)
    with tempfile.TemporaryDirectory() as d:
        san = h._compile_c(
            item.c_src,
            ["-O1", "-fsanitize=undefined", "-fno-sanitize-recover=all"],
            d, "san")
        o0 = h._compile_c(item.c_src, ["-O0"], d, "o0")
        tgt = h._compile_target(item.target_src, item.lang, d, "tgt")
        if not all((san, o0, tgt)):
            return LabelEvidence("uncompilable", False, "", "",
                                 f"compile san={bool(san)} o0={bool(o0)} tgt={bool(tgt)}")
        san_run = h._run([san, *argv])
        c_run = h._run([o0, *argv])
        t_a = h._run([tgt, *argv])
        t_b = h._run([tgt, *argv])

    tgt_det = (t_a.returncode == t_b.returncode and t_a.stdout == t_b.stdout)
    tgt_defined = (t_a.target_outcome_defined(item.lang)
                   and t_b.target_outcome_defined(item.lang) and tgt_det)

    if san_run.ub_trapped:
        if tgt_defined:
            return LabelEvidence("divergent", True, "", t_a.stdout,
                                 f"C UB-trapped ({san_run.ub_category!r}); "
                                 f"target defined rc={t_a.returncode}")
        return LabelEvidence("inconclusive", True, "", t_a.stdout,
                             "C UB-trapped but target not defined/deterministic")

    # C is well-defined on this input.
    c_defined = (c_run.returncode == 0)
    if c_defined and tgt_defined and t_a.returncode == 0:
        if c_run.stdout == t_a.stdout:
            return LabelEvidence("equivalent", False, c_run.stdout, t_a.stdout,
                                 "both defined, identical output")
        return LabelEvidence("divergent", False, c_run.stdout, t_a.stdout,
                             "both defined, differing output (value divergence)")
    return LabelEvidence("inconclusive", False, c_run.stdout, t_a.stdout,
                         f"c_rc={c_run.returncode} tgt_defined={tgt_defined}")


# --------------------------------------------------------------------------- #
# Establishing & confirming the ground truth.
# --------------------------------------------------------------------------- #
@dataclass
class GTResult:
    item_id: str
    lang: str
    klass: str
    declared_label: str
    observed_label: str
    agrees: bool
    detail: str


@dataclass
class GTReport:
    available: bool
    total_items: int
    langs: Tuple[str, ...]
    results: List[GTResult] = field(default_factory=list)

    @property
    def labeled(self) -> List[GTResult]:
        return [r for r in self.results
                if r.observed_label in ("divergent", "equivalent")]

    @property
    def agreements(self) -> int:
        return sum(1 for r in self.results if r.agrees)

    @property
    def disagreements(self) -> List[GTResult]:
        return [r for r in self.results
                if r.observed_label in ("divergent", "equivalent") and not r.agrees]

    @property
    def ok(self) -> bool:
        # Every sanitizer-labeled item must match its declared label, and at
        # least one item of each label must have been observed.
        lab = self.labeled
        if not lab:
            return False
        if self.disagreements:
            return False
        kinds = {r.observed_label for r in lab}
        return {"divergent", "equivalent"}.issubset(kinds)


def _sample_indices(items: List[GTItem], per_class: int) -> List[int]:
    """A deterministic spread: the first ``per_class`` items of every
    (lang, klass) bucket — covering every family, both languages, both labels."""
    seen: Dict[Tuple[str, str], int] = {}
    picked: List[int] = []
    for idx, it in enumerate(items):
        key = (it.lang, it.klass)
        n = seen.get(key, 0)
        if n < per_class:
            picked.append(idx)
            seen[key] = n + 1
    return picked


def establish_ground_truth(langs: Tuple[str, ...] = ("rust", "go"),
                           status: Optional[ToolchainStatus] = None,
                           sample_per_class: Optional[int] = 1) -> GTReport:
    """Run the sanitizer labeler over the corpus (or a per-family sample) and
    compare the authoritative observed label against the declared label."""
    st = status or toolchain_available()
    items = enumerate_corpus(langs)
    avail_langs = tuple(l for l in langs if st.full_for(l))
    rep = GTReport(available=bool(avail_langs), total_items=len(items),
                   langs=avail_langs)
    if not avail_langs:
        return rep
    items = [it for it in items if it.lang in avail_langs]
    h = ReexecHarness(st)
    if sample_per_class is None:
        chosen = list(range(len(items)))
    else:
        chosen = _sample_indices(items, sample_per_class)
    for idx in chosen:
        it = items[idx]
        ev = label_item(h, it)
        rep.results.append(GTResult(
            it.item_id, it.lang, it.klass, it.declared_label,
            ev.observed_label, ev.observed_label == it.declared_label, ev.detail))
    return rep


@dataclass
class GTConfirmation:
    available: bool
    ok: bool
    corpus_size: int
    n_langs: int
    report: GTReport


def confirm_ground_truth(langs: Tuple[str, ...] = ("rust", "go"),
                         sample_per_class: Optional[int] = 1) -> GTConfirmation:
    """Confirm the labeled set is (a) large enough (>=500 across >=2 pairs) and
    (b) faithfully labeled — every sampled sanitizer-observed label matches the
    declared label."""
    full = enumerate_corpus(langs)
    rep = establish_ground_truth(langs, sample_per_class=sample_per_class)
    n_langs = len({it.lang for it in full})
    size_ok = len(full) >= 500 and n_langs >= 2
    ok = bool(rep.available) and rep.ok and size_ok
    return GTConfirmation(available=bool(rep.available), ok=ok,
                          corpus_size=len(full), n_langs=n_langs, report=rep)


def corpus_stats(langs: Tuple[str, ...] = ("rust", "go")) -> Dict[str, object]:
    """Class/label/lang distribution of the labeled corpus (for the paper's
    'ground-truth set' table)."""
    items = enumerate_corpus(langs)
    by_label: Dict[str, int] = {}
    by_lang: Dict[str, int] = {}
    by_class: Dict[str, int] = {}
    for it in items:
        by_label[it.declared_label] = by_label.get(it.declared_label, 0) + 1
        by_lang[it.lang] = by_lang.get(it.lang, 0) + 1
        by_class[it.klass] = by_class.get(it.klass, 0) + 1
    return {
        "total": len(items),
        "n_langs": len(by_lang),
        "by_label": by_label,
        "by_lang": by_lang,
        "by_class": by_class,
    }


GROUND_TRUTH_SPI = {
    "enumerate_corpus": enumerate_corpus,
    "label_item": label_item,
    "establish_ground_truth": establish_ground_truth,
    "confirm_ground_truth": confirm_ground_truth,
    "corpus_stats": corpus_stats,
}


if __name__ == "__main__":  # pragma: no cover
    stats = corpus_stats()
    print(f"corpus: {stats['total']} items, {stats['n_langs']} language pairs")
    print(f"  by label: {stats['by_label']}")
    print(f"  by lang:  {stats['by_lang']}")
    print(f"  by class: {stats['by_class']}")
    conf = confirm_ground_truth()
    print(f"available={conf.available} ok={conf.ok} "
          f"size={conf.corpus_size} langs={conf.n_langs}")
    print(f"  sampled {len(conf.report.results)} items, "
          f"{conf.report.agreements} agree, "
          f"{len(conf.report.disagreements)} disagree")
    for r in conf.report.disagreements:
        print(f"  DISAGREE {r.item_id}: declared={r.declared_label} "
              f"observed={r.observed_label} :: {r.detail}")
