"""Generated migration-scale paper section (100_STEPS step 155).

The paper's scale subsection should be a view of the executable corpus, not a
hand-maintained copy of headline numbers.  The structural census is generated
without toolchains; the optional live-sample paragraph is generated only by
running the real ``large_scale_study`` confirmation and reports unavailable
toolchains honestly.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Mapping, Optional

from . import large_scale_study as ls

ROOT = Path(__file__).resolve().parents[2]
GENERATED_SECTION = ROOT / "docs" / "generated_scale_section.tex"

BEGIN_CORE = "% BEGIN AUTOGENERATED SCALE STRUCTURAL CORE"
END_CORE = "% END AUTOGENERATED SCALE STRUCTURAL CORE"


def _latex_int(value: object) -> str:
    return f"{int(value):,}".replace(",", "{,}")


def _percent(numerator: object, denominator: object) -> str:
    if int(denominator) == 0:
        return "0.00\\%"
    return f"{(100.0 * int(numerator) / int(denominator)):.2f}\\%"


def _by_class_rows(by_class: Mapping[str, int]) -> str:
    labels = {
        "div_by_zero": "division by zero",
        "oob_read": "out-of-bounds read",
        "oversized_shift": "oversized shift",
        "signed_overflow": "signed overflow",
        "safe_add": "safe addition",
        "safe_mod": "safe modulo",
        "safe_mul": "safe multiplication",
        "safe_shift": "safe shift",
    }
    lines = []
    for klass, count in sorted(by_class.items()):
        family = "UB-rooted divergent" if not klass.startswith("safe_") else "defined equivalent"
        escaped_klass = klass.replace("_", r"\_")
        lines.append(
            f"{escaped_klass} & {labels.get(klass, klass)} & "
            f"{family} & {_latex_int(count)} \\\\"
        )
    return "\n".join(lines)


def render_scale_structural_core(census: Optional[Dict[str, object]] = None) -> str:
    census = census or ls.corpus_census(ls.generate_corpus())
    by_pair = dict(census["by_pair"])  # type: ignore[arg-type]
    by_label = dict(census["by_label"])  # type: ignore[arg-type]
    by_class = dict(census["by_class"])  # type: ignore[arg-type]
    balance = int(census["label_balance_delta"])

    return "\n".join([
        BEGIN_CORE,
        r"\subsection{Migration-Scale Corpus (RQ1b)}\label{sec:eval-large-scale}",
        "",
        "Hand-picked witnesses do not establish migration-scale trust.  The artifact",
        r"therefore includes a deterministic generator",
        r"(\texttt{src/ub\_oracle/large\_scale\_study.py}) that enumerates",
        rf"\textbf{{{_latex_int(census['n_items'])}}} genuinely distinct",
        rf"C$\to$\{{Rust,Go\}} programs totaling \textbf{{{_latex_int(census['total_loc'])}}}",
        "counted source+target LOC.  The generator bakes \\emph{defined} operands into",
        "each source file and reads only the UB-triggering operand from \\texttt{argv};",
        "the census is therefore a structural claim, not a sampling estimate.",
        rf"Every program hash is unique ({_latex_int(census['n_distinct_programs'])}/"
        rf"{_latex_int(census['n_items'])}), and the declared labels are deliberately",
        rf"balanced: {_latex_int(by_label['divergent'])} divergent vs. "
        rf"{_latex_int(by_label['equivalent'])} equivalent "
        rf"({ _percent(balance, census['n_items']) } delta).",
        "",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Migration-scale corpus census, generated directly by",
        r"\texttt{paper\_scale\_section.py} from \texttt{corpus\_census}.}",
        r"\label{tab:large-scale}",
        r"\begin{tabular}{@{}lr@{}}",
        r"\toprule",
        r"Quantity & Count \\",
        r"\midrule",
        rf"Programs / distinct program hashes & {_latex_int(census['n_items'])} / "
        rf"{_latex_int(census['n_distinct_programs'])} \\",
        rf"C LOC / target LOC & {_latex_int(census['c_loc'])} / "
        rf"{_latex_int(census['target_loc'])} \\",
        rf"Total LOC & {_latex_int(census['total_loc'])} \\",
        rf"C$\to$Rust / C$\to$Go programs & {_latex_int(by_pair['rust'])} / "
        rf"{_latex_int(by_pair['go'])} \\",
        rf"Divergent / equivalent labels & {_latex_int(by_label['divergent'])} / "
        rf"{_latex_int(by_label['equivalent'])} \\",
        rf"Label-balance delta & {_latex_int(balance)} "
        rf"({_percent(balance, census['n_items'])}) \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Scale-corpus family mix; every row is counted over the full",
        r"60k-program population rather than sampled.}",
        r"\label{tab:large-scale-classes}",
        r"\begin{tabular}{@{}lllr@{}}",
        r"\toprule",
        r"Class & Pattern & Family & Count \\",
        r"\midrule",
        _by_class_rows(by_class),
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
        "The live part remains honest about cost: CI can execute a deterministic seeded",
        "sample rather than compiling the full million-LOC corpus on every run, and",
        r"\texttt{available=false} is reported instead of invented evidence when a",
        "required toolchain is missing.  The same verdict-layer hash discipline used by",
        "the parallel, sharded, distributed-manifest, memory-bounded, and result-store",
        "checks excludes timing and host metadata from semantic reproducibility.",
        END_CORE,
    ])


def render_live_sample_note(sample_size: int = 12, seed: int = 0xC0FFEE) -> str:
    report = ls.confirm_large_scale_study(sample_size=sample_size, seed=seed)
    if not report.available:
        return (
            "A live compiler sample was not emitted in this environment: the full "
            "\\texttt{clang}/UBSan plus target toolchain was unavailable, so the "
            "artifact records \\texttt{available=false} rather than fabricating a "
            "verdict."
        )
    ag = report.aggregates
    return (
        rf"On the current full toolchain, \texttt{{make large-scale}} confirms "
        rf"{int(ag.get('confirmed_divergent', 0))} divergent and "
        rf"{int(ag.get('confirmed_equivalent', 0))} equivalent sampled items with "
        rf"{int(ag.get('agree', 0))}/{int(ag.get('executed', 0))} observed labels "
        rf"matching the declared ground truth (verdict-layer hash prefix "
        rf"\texttt{{{report.content_hash[:12]}}})."
    )


def render_scale_section(
    *,
    include_live: bool = True,
    sample_size: int = 12,
    seed: int = 0xC0FFEE,
) -> str:
    lines = [
        "% Auto-generated by ub_oracle.paper_scale_section; do not hand-edit numbers.",
        render_scale_structural_core(),
    ]
    if include_live:
        lines.extend(["", render_live_sample_note(sample_size=sample_size, seed=seed)])
    return "\n".join(lines) + "\n"


def extract_structural_core(text: str) -> str:
    start = text.index(BEGIN_CORE)
    end = text.index(END_CORE) + len(END_CORE)
    return text[start:end]


def write_scale_section(
    path: Path = GENERATED_SECTION,
    *,
    include_live: bool = True,
    sample_size: int = 12,
    seed: int = 0xC0FFEE,
) -> str:
    text = render_scale_section(
        include_live=include_live,
        sample_size=sample_size,
        seed=seed,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class ScaleSectionCheck:
    ok: bool
    structural_fresh: bool
    live_ok: bool
    live_available: bool
    content_hash: str

    def to_dict(self) -> Dict[str, object]:
        return {
            "ok": self.ok,
            "structural_fresh": self.structural_fresh,
            "live_ok": self.live_ok,
            "live_available": self.live_available,
            "content_hash": self.content_hash,
        }


def confirm_scale_paper_section(
    path: Path = GENERATED_SECTION,
    *,
    run_live: bool = False,
    sample_size: int = 6,
    seed: int = 0xC0FFEE,
) -> ScaleSectionCheck:
    expected_core = render_scale_structural_core()
    try:
        actual = path.read_text(encoding="utf-8")
        actual_core = extract_structural_core(actual)
    except (OSError, ValueError):
        actual = ""
        actual_core = ""
    structural_fresh = actual_core == expected_core

    live_ok = True
    live_available = False
    if run_live:
        report = ls.confirm_large_scale_study(sample_size=sample_size, seed=seed)
        live_ok = report.ok
        live_available = report.available

    content_hash = hashlib.sha256(actual.encode("utf-8")).hexdigest() if actual else ""
    return ScaleSectionCheck(
        ok=bool(structural_fresh and live_ok),
        structural_fresh=structural_fresh,
        live_ok=live_ok,
        live_available=live_available,
        content_hash=content_hash,
    )


if __name__ == "__main__":  # pragma: no cover
    print(render_scale_section(), end="")
